# Generated by Django 5.0.3 on 2024-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_age_student_email_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=100)),
                ('Hero', models.CharField(max_length=30)),
                ('Heroine', models.CharField(max_length=20)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
