# Generated by Django 5.0.3 on 2024-04-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_company', models.CharField(max_length=100)),
                ('seats_available', models.IntegerField()),
            ],
        ),
    ]
