# Generated by Django 5.0.3 on 2024-04-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
